set nocompatible

set showmode
set number
set ruler
set hlsearch
set laststatus=2
set colorcolumn=80

syntax on
colorscheme github

highlight ColorColumn ctermbg=0 guibg=lightgrey
highlight Comment ctermfg=green

" Tab configuration
set autoindent
set expandtab
set shiftround
set shiftwidth=4
set smarttab
set tabstop=4

" Remap reverse tab to Alt+Shift
" for command mode
nnoremap <S-Tab> <<
" for insert mode
inoremap <S-Tab> <C-d>

" Remap tab for block selection
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
inoremap <S-Tab> <C-D>
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv