set nocompatible

set showmode
set number
set ruler
set hlsearch
set laststatus=2
set colorcolumn=80
set mouse=a

syntax on

" use a slightly darker background, like GitHub inline code blocks
let g:github_colors_soft = 1

" use the dark theme
set background=dark

" more blocky diff markers in signcolumn (e.g. GitGutter)
let g:github_colors_block_diffmark = 0

colorscheme github

highlight ColorColumn ctermbg=0 guibg=lightgrey

" Tab configuration
set autoindent
set expandtab
set shiftround
set shiftwidth=4
set smarttab
set tabstop=4

set splitbelow
set splitright

" Tabline/Buffer line
set showtabline=2
set tabline="%1T"

" Remap change tab
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

" Remap reverse tab to Alt+Shift
" for command mode
nnoremap <S-Tab> <<
" for insert mode
inoremap <S-Tab> <C-d>

" Remap tab for block selection
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
inoremap <S-Tab> <C-D>
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv